### ISSUE TITLE
Found issue between different servos

### ISSUE THREAD

**Issue by USAFAN** [robottini/grbl-servo#25]
I noticed that using a 20kg servo would make the board disconnect from the gcode sender. I switched it to a sg90 toy servo(one of those typical plastic small ones) and it now will operate commands and gcode without turning off when shifting positions.

**Comment by robottini** [comment]
How do you provide the power supply to the servo? From the CNC shield or from an external power supply?

**Comment by USAFAN** [comment]
@robottini You were spot on, feeling silly for not trying that before commenting. Big thanks!
